### ISSUE TITLE
Documentation Pipeline Failing on GitHub Pages: Just-the-docs Theme Not Found

### ISSUE THREAD

**Issue by gioisco** [RIP-Comm/sossoldi#175]
In my fork of the 'sossoldi' repository, I activated GitHub Pages following the [the sossoldi guide](https://rip-comm.github.io/sossoldi/doc-guide.html) several months ago.

Recently, I created new pages for the sossoldi documentation, but I noticed that the pipeline for building the documentation doesn't work. This is the error I encountered.

<p>
<details>
<summary>Error log:</summary>

```
Run actions/jekyll-build-pages@v1
  with:
    source: ./docs
    destination: ./docs/_site
    future: false
    build_revision: 85cfb429e8c6b1f09d4905f82678b6dbdc145cd7
    verbose: true
    token: ***
/usr/bin/docker run --name ghcrioactionsjekyllbuildpagesv1013_403cf3 --label 844f6f --workdir /github/workspace --rm -e "INPUT_SOURCE" -e "INPUT_DESTINATION" -e "INPUT_FUTURE" -e "INPUT_BUILD_REVISION" -e "INPUT_VERBOSE" -e "INPUT_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/sossoldi/sossoldi":"/github/workspace" ghcr.io/actions/jekyll-build-pages:v1.0.13
The following gems are missing
 * jekyll (4.3.3)
 * just-the-docs (0.7.0)
 * addressable (2.8.6)
 * i18n (1.14.1)
 * jekyll-sass-converter (3.0.0)
 * mercenary (0.4.0)
 * rouge (4.2.0)
 * terminal-table (3.0.2)
 * rake (13.0.6)
 * public_suffix (5.0.4)
 * concurrent-ruby (1.2.2)
 * sass-embedded (1.69.5)
 * listen (3.8.0)
 * rexml (3.2.6)
 * unicode-display_width (2.5.0)
 * google-protobuf (3.25.1)
 * rb-inotify (0.10.1)
 * ffi (1.16.3)
Install missing gems with `bundle install`
Warning: The github-pages gem can't satisfy your Gemfile's dependencies. If you want to use a different Jekyll version or need additional dependencies, consider building Jekyll site with GitHub Actions: https://jekyllrb.com/docs/continuous-integration/github-actions/
/usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/theme.rb:84:in `rescue in gemspec': The just-the-docs theme could not be found. (Jekyll::Errors::MissingDependencyException)
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/theme.rb:81:in `gemspec'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/theme.rb:19:in `root'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/theme.rb:12:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/site.rb:439:in `new'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/site.rb:439:in `configure_theme'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/site.rb:55:in `config='
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/site.rb:23:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/local/bundle/gems/github-pages-232/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-232/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:25:in `load'
	from /usr/local/bundle/bin/github-pages:25:in `<main>'
/usr/local/lib/ruby/3.3.0/rubygems/dependency.rb:301:in `to_specs': Could not find 'just-the-docs' (>= 0) among 179 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/github/home/.local/share/gem/ruby/3.3.0:/usr/local/lib/ruby/gems/3.3.0:/usr/local/bundle' , execute `gem env` for more information
	from /usr/local/lib/ruby/3.3.0/rubygems/dependency.rb:313:in `to_spec'
	from /usr/local/lib/ruby/3.3.0/rubygems/specification.rb:953:in `find_by_name'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/theme.rb:82:in `gemspec'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/theme.rb:19:in `root'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/theme.rb:12:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/site.rb:439:in `new'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/site.rb:439:in `configure_theme'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/site.rb:55:in `config='
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/site.rb:23:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/local/bundle/gems/github-pages-232/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-232/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:25:in `load'
	from /usr/local/bundle/bin/github-pages:25:in `<main>'
Error:  Logging at level: debug Configuration file: /github/workspace/./docs/_config.yml Theme: just-the-docs github-pages 232 | Error: The just-the-docs theme could not be found. 
```

</details>
</p>

After investigating the upstream repository, I discovered that the job stopped working about 6 months ago, in commit 366238e, due to the same error. 

```log
Logging at level: debug Configuration file: /github/workspace/./docs/_config.yml Theme: just-the-docs github-pages 228 | 
Error: The just-the-docs theme could not be found. 
```

None of the subsequent builds of the `pages-build-deployment` action have finished successfully since then.

However, I'm confused about how it is still possible for me to see the documentation with the just-the-docs theme by visiting https://rip-comm.github.io/sossoldi/, but not in my repository at https://gioisco.github.io/sossoldi/.

Do you have any suggestions on how to resolve this issue?

**Comment by gioisco** [comment]
I tried to update my [database-doc](https://github.com/gioisco/sossoldi/tree/database-doc) branch by rebasing it onto the latest `main` at commit `acc9792`, but the issue is still there 😢
